notifications:
  webhooks:
    urls:
      - https://hooks.glipdemo.com/webhook/8f2be274-8c34-4c49-8f19-c1afdcf077c9
    on_success: change # default: always
    on_failure: always # default: always
    on_start: change   # default: always
