notifications:
  webhooks:
    urls:
      - https://hooks.glipdemo.com/webhook/2a170881-6b53-4482-94b9-cd952591cba4
    on_success: change # default: always
    on_failure: always # default: always
    on_start: change   # default: always
